#%RAML 1.0 SecurityScheme
type: OAuth 2.0
displayName: Token delivery described as query parameter only
settings:
  accessTokenUri: https://query.com/token
  authorizationUri: https://query.com/auth
  authorizationGrants: client_credentials
  scopes: [query]
describedBy:
  queryParameters:
    access_token:
      type: string
      description: Apply access token as a query here.
