#%RAML 1.0
title: APIC-631


types:
  test1:
    properties:
      names1: string[] | nil
  test2:
    type: string[] | nil
  test3:
    type: string[]
  test4:
    properties:
      names1: string[]
  test5:
    type: string[]
  test8:
    properties:
      names8: number[]