#%RAML 0.8
title: Arabic Test 0.8

version: v1

/stuff:
  get:
    responses:
      200:
        description: بينغ
        body:
          application/json:
            example:
              الحالة: حسنا
              message: Shop in الممل
