#%RAML 1.0 NamedExample
 post-body-request-single-example:
    address: 250 HIDEOUT LN
    comments: Orgin comments entered here.
    references:
    - referenceType: Delivery Note
      referenceValue: '7328'