#%RAML 1.0 DataType

description: |
  A dimmensions of an object like image.

type: object
properties:
  width:
    type: number
    description: |
      Width of the shape.
  height:
    type: number
    description: |
      Height of the shape.
  unit?:
    type: string
    default: px
    description: |
      A unit that describes the dimension. It can be, for example, `px` for
      pixels, `pt` for points, `%` for percentage.
example:
  width: 200
  height: 160
